name: SimpleHome
main: net.immortal_forces.silence.plugin.simplehome.SimpleHome
version: 1.5
commands:
  home:
    description: Teleports you to your home
    usage: /home
  sethome:
    description: Sets your home
    usage: /sethome