name: SimpleHome
main: com.bukkit.silence.simplehome.SimpleHome
version: 1.2
commands:
  home:
    description: Teleports you to your home
    usage: /home
  sethome:
    description: Sets your home
    usage: /sethome