name: SimpleHome
main: com.bukkit.silence.simplehome.SimpleHome
version: 1.1
commands:
  home:
    description: Teleports you somewhere
    usage: /home
  sethome:
    description: Clears your inventory
    usage: /sethome